version: "3"

services:

  nats-server:
    image: nats:2.10.12-alpine3.19

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: "us-east1-docker.pkg.dev/airy-gate-419018/image-registry/client-gateway"
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: "us-east1-docker.pkg.dev/airy-gate-419018/image-registry/auth-ms"
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: "us-east1-docker.pkg.dev/airy-gate-419018/image-registry/products-ms"
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        # argumento de contrucción
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: "us-east1-docker.pkg.dev/airy-gate-419018/image-registry/orders-ms"
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: "us-east1-docker.pkg.dev/airy-gate-419018/image-registry/payments-ms"
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}